### ISSUE TITLE
NvimError: Cursor position outside buffer

### ISSUE THREAD

**Issue by wallace11** [philip-karlsson/bolt.nvim#10]
1. Installed via `Plug 'ripxorip/bolt.nvim', { 'do': ':UpdateRemotePlugins' }`
2. NVIM v0.4.2
3. Getting the following error upon typing `:Bolt`:
```
Error detected while processing function remote#define#request:
line    2:
Error invoking '~/.local/share/nvim/plugged/bolt.nvim/rplugin/python3/vim_tc_explorer:autocmd:TextChangedI:TC_Input' on
 channel 3 (python3-rplugin-host):
error caught in request handler '~/.local/share/nvim/plugged/bolt.nvim/rplugin/python3/vim_tc_explorer:autocmd:TextChan
gedI:TC_Input []':
Traceback (most recent call last):
  File "~/.local/share/nvim/plugged/bolt.nvim/rplugin/python3/vim_tc_explorer/__init__.py", line 128, in insert_changed

    self.TcExplorer.handle_input()
  File "~/.local/share/nvim/plugged/bolt.nvim/rplugin/python3/vim_tc_explorer/vim_tc_explorer.py", line 554, in handle_
input
    exp.window.cursor = (exp.selected + exp.headerLength, 0)
  File "/usr/lib/python3.7/site-packages/pynvim/api/window.py", line 27, in cursor
    return self.request('nvim_win_set_cursor', pos)
  File "/usr/lib/python3.7/site-packages/pynvim/api/common.py", line 51, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Cursor position outside buffer'
Press ENTER or type command to continue
```

**Comment by ripxorip** [comment]
Hi thanks for the bug report. I have not seen this behavior before. Is this report from a vanilla NeoVim or with other plugins running as well?

**Comment by wallace11** [comment]
Hey,
Sorry for the late response.
I could reproduce this issue with no other plugins installed.

**Comment by bscuron19** [comment]
Hi, I just found out about this plugin, and I find it very cool. However, I am having the same problem. Has anyone found a solution?

**Comment by ripxorip** [comment]
Are you still on the same version? I cant reproduce it no matter what I try. Are you running the latest version?

**Comment by anuvyklack** [comment]
```
Error detected while processing function remote#define#request:
line    2:
Error invoking '/home/anuvyklack/.local/share/nvim/site/pack/packer/start/bolt.nvim/rplugin/python3/vim_tc_explorer:autocmd:TextChangedI:TC_Input' on channel 3 (python3-rplugin-hos
t):
error caught in request handler '/home/anuvyklack/.local/share/nvim/site/pack/packer/start/bolt.nvim/rplugin/python3/vim_tc_explorer:autocmd:TextChangedI:TC_Input []':
Traceback (most recent call last):
  File "/home/anuvyklack/.local/share/nvim/site/pack/packer/start/bolt.nvim/rplugin/python3/vim_tc_explorer/__init__.py", line 128, in insert_changed
    self.TcExplorer.handle_input()
  File "/home/anuvyklack/.local/share/nvim/site/pack/packer/start/bolt.nvim/rplugin/python3/vim_tc_explorer/vim_tc_explorer.py", line 556, in handle_input
    exp.window.cursor = (exp.selected + exp.headerLength, 0)
  File "/usr/lib/python3/dist-packages/pynvim/api/window.py", line 27, in cursor
    return self.request('nvim_win_set_cursor', pos)
  File "/usr/lib/python3/dist-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Cursor position outside buffer
```

  Seem like I have the same problem. I am running the latest nightly build of Neovim, with pynvim version: 0.4.1

**Comment by ripxorip** [comment]
Hmm.. can you try to reproduce in a docker environment? Or can I? What system are you on?

**Comment by anuvyklack** [comment]
I don't know how to work with docker. I can, if you explain how. 

I am using Pop!_OS 20.10 which is Ubuntu 20.10 with a different gnome-shell. I'm using [neovim nightly](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) with `python3-pynvim` package version `0.4.1-2` from Ubuntu apt repo.
